@defaultUrl = http://localhost:3000/students/
@wrongId = 8ae9054b-2992-4447-944d-b24262ed924d

### This route returns all students
GET {{defaultUrl}}

### This route returns a student by their id
GET {{defaultUrl}}{{wrongId}}

### This route creates a new student
POST {{defaultUrl}}
Content-Type: application/json

{
    "student_name": "Og Silva Neto",
    "student_email": "ogsilvanetu@gmail.com"
}

### This route updates a student by their Id
PATCH {{defaultUrl}}...
Content-Type: application/json

{
    "student_name": "xxx",
    "student_email": "xxx"
}